version: 2.1
orbs:
  android: circleci/android@2.4.0

jobs:
  build-and-test:
    docker:
      - image: cimg/android:2023.11.1
    steps:
      - checkout
      - run:
          name: Set Permissions for Gradle Wrapper
          command: sudo chmod +x ./gradlew
      - run:
          name: Accept Android SDK Licenses
          command: (yes || true) | sdkmanager --licenses
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
      - run:
          name: Dependencies Download
          command: ./gradlew androidDependencies --no-daemon --no-configuration-cache
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - run:
          name: Build and Test
          command: ./gradlew lint build test --no-daemon --no-configuration-cache
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk

workflows:
  version: 2
  build:
    jobs:
      - build-and-test